package exception3;

public class Throw01_361p {

	public static void main(String[] args) {
		
		// throw는 예외상황이 아니지만 예외를 강제로 발생시킨다.
		
		System.out.println(Math.random());
		// Math.random()은 '0 <= 난수 < 1' 범위를 가지는 '난수'를 발생시키는 값이다.
		
	    System.out.println(Math.random(*10));

	}

}
